# Generated by Django 4.2.1 on 2023-06-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportshall",
            name="photo",
            field=models.ImageField(default="", upload_to="images"),
        ),
    ]
