# Generated by Django 4.2.1 on 2023-06-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0002_sportshall_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sportshall",
            name="photo",
            field=models.ImageField(
                default="", upload_to="../frontend/src/public/images"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_photo",
            field=models.ImageField(
                default="", upload_to="../frontend/src/public/images"
            ),
        ),
    ]
