# Generated by Django 4.2.1 on 2023-06-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0007_alter_user_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sport",
            name="sport_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
