# Generated by Django 4.2.1 on 2023-06-07 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0008_alter_sport_sport_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sportshall",
            name="sports",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_sport",
        ),
        migrations.CreateModel(
            name="UserSportInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sportista.sport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sportista.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SportsHallSportInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sportista.sport",
                    ),
                ),
                (
                    "sports_hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sportista.sportshall",
                    ),
                ),
            ],
        ),
    ]
