# Generated by Django 4.2.1 on 2023-06-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0012_day_rename_location_sportshall_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
