# Generated by Django 4.2.1 on 2023-06-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0013_alter_day_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sportshall",
            name="work_time_begin",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sportshall",
            name="work_time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sportshall",
            name="working_days",
            field=models.ManyToManyField(blank=True, to="sportista.day"),
        ),
    ]
