# Generated by Django 4.2.1 on 2023-06-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0014_alter_sportshall_work_time_begin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportshall",
            name="sports",
            field=models.ManyToManyField(blank=True, to="sportista.sport"),
        ),
    ]
