# Generated by Django 4.2.1 on 2023-06-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0015_sportshall_sports"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="available",
        ),
        migrations.AddField(
            model_name="appointment",
            name="capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UserAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_spots", models.IntegerField()),
                ("used_spots", models.IntegerField(default=0)),
                ("available", models.BooleanField(default=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sportista.appointment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sportista.user"
                    ),
                ),
            ],
        ),
    ]
