# Generated by Django 4.2.1 on 2023-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sportista",
            "0016_remove_appointment_available_appointment_capacity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_sports",
            field=models.ManyToManyField(blank=True, to="sportista.sport"),
        ),
        migrations.DeleteModel(
            name="UserSportInterest",
        ),
    ]
