# Generated by Django 4.2.1 on 2023-06-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0018_remove_user_user_sports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_photo",
            field=models.ImageField(upload_to="media/images"),
        ),
    ]
