# Generated by Django 4.2.1 on 2023-06-11 18:31

from django.db import migrations, models
import sportista.models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0019_alter_user_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_photo",
            field=models.ImageField(
                default=sportista.models.get_default_user_photo,
                upload_to="media/images",
            ),
        ),
    ]
