# Generated by Django 4.2.1 on 2023-06-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0020_alter_user_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_photo",
            field=models.ImageField(upload_to="media/images"),
        ),
    ]
