# Generated by Django 4.2.1 on 2023-06-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0021_alter_user_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="sport",
        ),
        migrations.AddField(
            model_name="appointment",
            name="sports",
            field=models.ManyToManyField(blank=True, to="sportista.sport"),
        ),
    ]
