# Generated by Django 4.2.1 on 2023-06-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0024_appointment_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sportshall",
            name="photo",
            field=models.ImageField(default="", upload_to="images"),
        ),
    ]
