# Generated by Django 4.2.1 on 2023-06-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0026_alter_sportshall_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userappointment",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
