# Generated by Django 4.2.1 on 2023-06-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0027_userappointment_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userappointment",
            name="price",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
