# Generated by Django 4.2.1 on 2023-06-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0028_remove_userappointment_price_alter_appointment_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportshall",
            name="email",
            field=models.CharField(default="sporthall@gmail.com", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sportshall",
            name="phone_number",
            field=models.CharField(default="+123 45 678 910", max_length=20),
            preserve_default=False,
        ),
    ]
