# Generated by Django 4.2.1 on 2023-06-16 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sportista", "0029_sportshall_email_sportshall_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userappointment",
            name="sport",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="sportista.sport",
            ),
            preserve_default=False,
        ),
    ]
