# Generated by Django 4.2.1 on 2023-06-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0030_userappointment_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
